### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by nateGeorge** [ifellows/wordcloud#1]
It doesn't seem like this is the place to contribute updates to the wordcloud package.  Is there a way for anyone to contribute to the package?

The only thing I've found so far is confusing behavior in the wordcloud function when min.freq is greater that max(freq).  In that case, it shows all words, but doesn't tell you that your minimum frequency is greater than the max frequency, and it's showing all words.

**Comment by ifellows** [comment]
The way this is typically done in github is to make enhancements and then submit a pull request. See for example: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by nateGeorge** [comment]
Oh ok, I just wasn't sure this was the right place to contribute because I've seen some SVN repos for other libraries, but couldn't find one for this.  Would you be ok adding in a warning/print statement that tells you if the min.freq exceeds max(freq)?
